from langchain_experimental.text_splitter import SemanticChunker
from langchain_community.embeddings import HuggingFaceEmbeddings

# Point to your local model directory
model_dir = "D:/huggingface_models/all-MiniLM-L6-v2"

# Initialize embeddings (offline)
embeddings = HuggingFaceEmbeddings(
    model_name=model_dir,  # Use local path
    model_kwargs={"device": "cpu"},  # Force CPU usage
    encode_kwargs={"normalize_embeddings": True}  # Optional for better performance
)

# Create chunker
text_splitter = SemanticChunker(
    embeddings,
    breakpoint_threshold_type="standard_deviation",
    breakpoint_threshold_amount=1.5  # Tune this (lower = more splits)
)

# Example usage
text = """
Lionel Andrés "Leo" Messi[note 1] (Spanish pronunciation: [ljoˈnel anˈdɾes ˈmesi] ⓘ; born 24 June 1987) is an Argentine professional footballer who plays as a forward for and captains both Major League Soccer club Inter Miami and the Argentina national team. Widely regarded as one of the greatest players of all time, Messi set numerous records for individual accolades won throughout his professional footballing career such as eight Ballon d'Or awards and eight times being named the world's best player by FIFA.[note 2] He is the most decorated player in the history of professional football having won 45 team trophies,[note 3] including twelve Big Five league titles, four UEFA Champions Leagues, two Copa Américas, and one FIFA World Cup. Messi holds the records for most European Golden Shoes (6), most goals in a calendar year (91), most goals for a single club (672, with Barcelona), most goals (474), hat-tricks (36) and assists (192) in La Liga, most assists (18) and goal contributions (32) in the Copa América, most goal contributions (21) in the World Cup, most international appearances (193) and international goals (112) by a South American male, and the second-most in the latter category outright. A prolific goalscorer and creative playmaker, Messi has scored over 850 senior career goals and has provided over 380 assists for club and country.[21]

Born in Rosario, Argentina, Messi relocated to Spain to join Barcelona at age 13, and made his competitive debut at age 17 in October 2004. He gradually established himself as an integral player for the club, and during his first uninterrupted season at age 22 in 2008–09 he helped Barcelona achieve the first treble in Spanish football. This resulted in Messi winning the first of four consecutive Ballons d'Or, and by the 2011–12 season he would set La Liga and European records for most goals in a season and establish himself as Barcelona's all-time top scorer. The following two seasons, he finished second for the Ballon d'Or behind Cristiano Ronaldo, his perceived career rival. However, he regained his best form during the 2014–15 campaign, where he became the all-time top scorer in La Liga, led Barcelona to a historic second treble, and won a fifth Ballon d'Or in 2015. He assumed Barcelona's captaincy in 2018 and won a record sixth Ballon d'Or in 2019. During his overall tenure at Barcelona, Messi won a club-record 34 trophies, including ten La Liga titles and four Champions Leagues, among others. Financial difficulties at Barcelona led to Messi signing with French club Paris Saint-Germain in August 2021, where he would win the Ligue 1 title during both of his seasons there. He joined Major League Soccer club Inter Miami in July 2023.

An Argentine international, Messi is the national team's all-time leading goalscorer and most-capped player. His style of play as a diminutive, left-footed dribbler, drew career-long comparisons with compatriot Diego Maradona, who described Messi as his successor. At the youth level, he won the 2005 FIFA World Youth Championship and gold medal in the 2008 Summer Olympics. After his senior debut in 2005, Messi became the youngest Argentine to play and score in a World Cup in 2006. Assuming captaincy in 2011, he then led Argentina to three consecutive finals in the 2014 FIFA World Cup, the 2015 Copa América and the Copa América Centenario, all of which they would lose. After initially announcing his international retirement in 2016, he returned to help his country narrowly qualify for the 2018 FIFA World Cup, which they would exit early. Messi and the national team finally broke Argentina's 28-year trophy drought by winning the 2021 Copa América, which helped him secure his seventh Ballon d'Or that year. He then led Argentina to win the 2022 Finalissima, as well as the 2022 FIFA World Cup, his country's third overall world championship and first in 36 years. This followed with a record-extending eighth Ballon d'Or in 2023, and a victory in the 2024 Copa América.

Messi has endorsed sportswear company Adidas since 2006. According to France Football, he was the world's highest-paid footballer for five years out of six between 2009 and 2014, and was ranked the world's highest-paid athlete by Forbes in 2019 and 2022. Messi was among Time's 100 most influential people in the world in 2011, 2012, and 2023. In 2020 and 2023, he was named the Laureus World Sportsman of the Year, the first team-sport athlete to win it. In 2020, Messi was named to the Ballon d'Or Dream Team and became the second footballer and second team-sport athlete to surpass $1 billion in career earnings. Following his arrival and impact on football in the US, Messi was named Time's Athlete of the Year in 2023, and was bestowed with the Presidential Medal of Freedom by US president Joe Biden in 2025.

Early life

Messi's childhood home in Rosario, Santa Fe.
Messi was born on 24 June 1987 in Rosario, Santa Fe Province.[22] He was the third of four children of Jorge Messi, a steel factory manager, and his wife Celia Cuccittini, who worked in a magnet manufacturing workshop. On his father's side, he is of Italian and Spanish descent, the great-grandson of immigrants from the north-central Adriatic Marche region of Italy, and on his mother's side, he has primarily Italian ancestry.[3] Growing up in a tight-knit, football-loving family, "Leo" developed a passion for the sport from an early age, playing constantly with his older brothers, Rodrigo and Matías, and his cousins, Maximiliano and Emanuel Biancucchi, both of whom became professional footballers.[23]

At the age of four he joined local club Grandoli, where he was coached by his father. Another early influence came from his maternal grandmother, Celia, who accompanied him to training and matches.[24] He was greatly affected by her death, shortly before his eleventh birthday. Since then, as a devout Catholic, he has celebrated his goals by looking up and pointing to the sky in tribute to his grandmother.[25][26]

Youth career
Newell's Old Boys
"When you saw him you would think: this kid can't play ball. He's a dwarf, he's too fragile, too small. But immediately you'd realise that he was born different, that he was a phenomenon and that he was going to be something impressive."

– Newell's Old Boys youth coach Adrián Coria shares his first impression of the 12-year-old Messi.[27]
Messi is a lifelong supporter of Newell's Old Boys, based in Rosario. When he was seven years old, he first started playing for Newell's. During the six years he played for them, he scored almost 500 goals, and was a member of "The Machine of '87", a nearly unbeatable youth side named for the year of their birth. Messi would regularly entertain crowds by performing ball tricks during half-time, when the first team played home games.[28][29][30] His goalscoring idol growing up was Brazilian striker Ronaldo, who Messi called "the best forward I've ever seen".[31]

His future as a professional player was threatened when, aged 10, he was diagnosed with a growth hormone deficiency. He began growth hormone therapy at age 11,[32] however his father's health insurance covered only two years of the therapy, which cost at least 1,000 pesos per month. Newell's agreed to contribute, but later reneged on their promise.[33] He was scouted by Buenos Aires club River Plate, whose playmaker Pablo Aimar he idolised.[34][35] It was speculated for a time that he failed to sign with River Plate due to his ill health; however, in a 2019 interview, Messi revealed that River Plate had wanted to sign him after he scored four goals at a trial, and even offered to pay for his medical treatment, however Newell's refused to release his player card, preventing the transfer.[36]

Barcelona

Messi enrolled at Barcelona's youth academy, La Masia, aged 13.
As the Messi family had relatives in Catalonia, they sought to arrange a trial with Barcelona in September 2000. First-team director Charly Rexach immediately wanted to sign him, but the board of directors hesitated; at the time it was highly unusual for European clubs to sign foreign players of such a young age. On 14 December, an ultimatum was issued for Barcelona to prove their commitment, and Rexach, with no other paper at hand, offered a contract on a paper napkin.[34][37] In February 2001, the family relocated to Barcelona, where they moved into an apartment near the club's stadium, Camp Nou. During his first year in Spain, Messi rarely played with the Infantiles due to a transfer conflict with Newell's; as a foreigner, he could only be fielded in friendlies and the Catalan league. Without football, he struggled to integrate into the team. He was reserved by nature, and was so quiet that some of his teammates initially believed he was mute. At home, he suffered from homesickness after his mother moved back to Rosario with his brothers and younger sister, María Sol, while he stayed in Barcelona with his father.[28][37][38]

After a year at Barcelona's youth academy, La Masia, Messi was finally enrolled in the Royal Spanish Football Federation (RFEF) in February 2002. Now he could play in all competitions, and quickly befriended his teammates, among whom were Cesc Fàbregas and Gerard Piqué.[39] After completing his growth hormone therapy at 14,[40] Messi became an integral part of the "Baby Dream Team", Barcelona's greatest-ever youth side. During his first full season (2002–03), he was top scorer with 36 goals in 30 games for the Cadetes A, who won an unprecedented treble of the league, the Spanish cup, and the Copa Catalunya.[39][41] In the Copa Catalunya final, their 4–1 victory over Espanyol became referred to in club lore as the partido de la máscara, the final of the mask. A week after suffering a broken cheekbone during a league match, Messi was allowed to start the game on the condition that he wear a plastic protector; soon hindered by the mask, he took it off and scored two goals in 10 minutes before his substitution.[42] At the close of the season, he received an offer to join Arsenal, his first from a foreign club. Although Fàbregas and Piqué soon left for England with their own offers, Messi chose to remain in Barcelona.[37][43][44]

Messi continued to progress through his club's ranks at a rapid pace, debuting for four youth teams during the 2003–04 season.[45] After being named player of the tournament in four separate international pre-season competitions with the Juvenil B, he played only one official match with the team before being promoted to the Juvenil A. In the Juvenil A he scored 18 goals in 11 league games.[46][47] Messi was then one of several youth players called up to strengthen a depleted first team during the international break. French winger Ludovic Giuly explained that Messi caught everyone's attention in a training session with Frank Rijkaard's first team: "He destroyed us all... They were kicking him all over the place to avoid being ridiculed by this kid, he just got up and kept on playing. He would dribble past four players and score a goal. Even the team's starting centre-backs were nervous. He was an alien."[48]

"It seemed as if he had been playing with us all his life."

– Barcelona's then assistant coach Henk ten Cate on Messi's first-team debut.[49]
At 16 years, four months, and 23 days old, Messi made his first-team debut when he came on in the 75th minute during a friendly against José Mourinho's Porto on 16 November 2003.[37][50] His performance, creating two chances and a shot on goal, impressed the technical staff, and he subsequently began training daily with the club's reserve side, Barcelona B, as well as weekly with the first team.[51] After his first training session with the senior squad, Barça's new star player, Ronaldinho, told his teammates that he believed the 16-year-old would become an even better player than himself.[52] Ronaldinho soon befriended Messi, whom he called "little brother". This greatly eased Messi's transition into the first team.[53][54]

To gain further match experience, Messi joined Barcelona C in addition to the Juvenil A, playing his first game for the third team on 29 November. He helped save them from the relegation zone of the Tercera División, scoring five goals in ten games, including a hat-trick in eight minutes during a Copa del Rey match while man-marked by Sevilla's Sergio Ramos.[46][55] His progress was reflected in his first professional contract, signed on 4 February 2004, which lasted until 2012 and contained an initial buyout clause of €30 million. A month later, on 6 March, he made his debut for Barcelona B in the Segunda División B, and his buyout clause automatically increased to €80 million.[46][56] He played five games with the B team that season but did not score.[57] Physically he was weaker than his opponents, who were often much older and taller, and in training he worked on increasing his muscle mass and overall strength in order to be able to shake off defenders. Towards the end of the season, he returned to both youth teams, helping the Juvenil B win the league. He finished the campaign having scored goals for four of his five teams, with a total of 36 goals in all official competitions.[46][55]

Club career
Main article: Career of Lionel Messi § Club career
Barcelona
2004–2008: Rise to the first team

Messi (pictured in 2005) at the age of 18 playing for FC Barcelona, where he played for 17 years.
Messi began the 2004–05 season as a guaranteed starter for the Barcelona B team, but after some lobbying by the senior players, he was promoted to the first team by manager Frank Rijkaard.[52] He made his La Liga debut for Barcelona on 16 October 2004 against Espanyol,[37] and scored his first senior goal on 1 May 2005 against Albacete, from an assist by Ronaldinho, becoming at that time the youngest-ever scorer for the club.[58][59] At 17 years, three months, and 22 days old, he was at the time the youngest player to represent Barcelona in an official competition, and the club won the league title during that season.[54][60]

On his 18th birthday, he signed his first contract as a senior team player, a five-year contract through 2010 with a release clause of €150 million.[61] Three months later, as his performance continued to make waves, his contract was updated to a nine-year contract, doubling his salary and keeping him at the club until 2014.[56][62]

Barcelona began the 2005–06 season by winning the Supercopa de España without Messi, who was not selected to participate in the competition.[19] By the end of the season, the team won La Liga again as well as the UEFA Champions League, although Messi did not play in the final for the latter due to injury.[63][64]

During the 2006–07 season, Messi scored his first hat-trick in a Clásico against Real Madrid, the first player to do so in 12 years.[65] An incredibly finesse goal from Messi against Getafe and another goal scored by a handball against Espanyol gained notice for their similarities to the two famous goals scored by fellow Argentine Diego Maradona in the 1986 World Cup match against England, drawing comparisons between the two that Messi would face throughout his career.[66][67][68] The team finished the season with only one trophy – the 2006 Supercopa de España.

Barcelona finished the next 2007–08 season trophyless, leading to Rijkaard's departure.[69]

2008–2012: Success under Pep Guardiola
At the beginning of the 2008–09 season, his first under Barcelona's new manager, former captain Pep Guardiola, Messi was given the number 10 shirt.[70] Over time, he effectively became the tactical focal point of Guardiola's possession-based system, increasing his goalscoring rate as a result.[71] During that season, Messi scored 38 total goals, and alongside Samuel Eto'o and Thierry Henry, contributed to a total of 100 goals in all competitions, a record at the time for the club.[72][73] Messi played as a false nine for the first time in a Clásico against Real Madrid, setting up his side's first goal and scoring twice in the team's greatest-ever score at Santiago Bernabéu Stadium.[74][75] He played his first final, winning the Copa del Rey.[76] In addition, Barcelona won the La Liga title and later won the Champions League, thus achieving the first treble in the history of Spanish football.[77]


Messi during the 2009 Joan Gamper Trophy against Manchester City.
During the first half of the 2009–10 season, Barcelona would also win the Supercopa de España, UEFA Super Cup and FIFA Club World Cup, resulting in becoming the first club to achieve the sextuple.[78][79] Messi finished as the Champions League top scorer, the youngest in the tournament's history.[80] For his efforts in 2009, Messi won the Ballon d'Or and the FIFA World Player of the Year award.[81] Messi scored a total of 47 goals in all competitions, equaling Ronaldo's club record from the 1996–97 campaign.[82][83] He finished the season as top scorer in the Champions League,[84] and La Liga, winning his second consecutive league trophy and earned his first European Golden Shoe.[83][85] After the team won the Champions League, he signed a new 7-year contract through 2016.[61]

In the 2010–11 campaign, Messi won the Supercopa de España,[86] Champions League,[87] and a third consecutive La Liga title. His club performances in 2010 earned him his second consecutive Ballon d'Or.[88] Messi was the top scorer in the Champions League, for the third consecutive year,[89] and the league's top scorer and assist provider.[90][91] He became Barcelona's all-time single-season top scorer with 53 goals.[90][92]

"I feel sorry for those who want to compete for Messi's throne – it's impossible, this kid is unique."

– Pep Guardiola after Messi became Barcelona's all-time top scorer at the age of 24 in March 2012[93]
Messi began the 2011–12 season winning both the Spanish and European Super Cups trophies.[94][95] At the close of the year, he won the FIFA Club World Cup and earned the Golden Ball for a second time.[96] For his efforts in 2011, he received the FIFA Ballon d'Or, becoming only the fourth player in history to win the Ballon d'Or three times,[97] and the inaugural UEFA Best Player in Europe Award.[98] During the year 2012, Messi became the second player to be top scorer in four Champions League campaigns.[99][100] Messi became the top goalscorer in Barcelona's history at 24 years old, overtaking the 57-year record of César Rodríguez's 232 goals with a hat-trick against Granada.[101] He finished the season as league top scorer in Spain and Europe for a second time, with 50 goals, a La Liga record, while his 73 goals in all competitions made him the single-season top scorer in the history of European club football excluding regional and local competitions.[102][103] The team would also win the Copa del Rey that season, their 14th trophy under Guardiola, who resigned following the season after a four-year cycle of success.[104]

2012–2014: Record-breaking year and Messidependencia

Messi scored a record-breaking 91 goals with Argentina (above) and Barcelona (below) in 2012.
For the start of the 2012–13 season, Barcelona had virtually secured their La Liga title by the start of 2013.[105] A double scored against Real Betis saw Messi becoming Barcelona's all-time top scorer in La Liga, and surpassed Gerd Müller's record of most goals scored in a calendar year; Messi would score a record 91 goals in all competitions for Barcelona and Argentina throughout 2012.[106][107] Messi again won the FIFA Ballon d'Or, becoming the first player in history to win the Ballon d'Or four times.[107][108] He signed a new contract committing himself to the club through 2018, and wore the captain's armband for the first time in a league match against Rayo Vallecano.[109][110][111] The team would win La Liga again that year, Messi's sixth, equalling Real Madrid's 100-point record of the previous season. With 60 goals in all competitions, including 46 goals in La Liga, he finished the campaign as league top scorer in Spain and Europe for the second consecutive year, becoming the first player in history to win the European Golden Shoe three times.[112]

Messi's overall input into the team's attack had increased significantly. Whereas he contributed to 24% of the team's goals in their treble-winning campaign in 2008–09, this number rose to more than 40% by the end of the 2012–13 season.[113] These statistics, as well as lopsided losses in the Champions League where Messi was unfit, gave credence to the notion of Messidependencia, Barcelona's perceived tactical and psychological dependence on their star player.[114]

To offset the load on Messi, Barcelona would sign Brazilian forward Neymar from Santos before the 2013–14 season.[115] The team would win the Supercopa de España at the beginning of the season.[116] Messi finished the campaign with his worst output in five seasons, though he still managed to score 41 goals in all competitions.[117] For the first time in five years, Barcelona ended the season without a major trophy.[118]

2014–2017: Arrival of Luis Enrique and birth of MSN

Messi dribbling past Patrice Evra of Juventus during the 2015 UEFA Champions League final.
Barcelona hired coach Luis Enrique before the 2014–15 season, and would continue to aid Messi in the attack by signing Uruguayan forward Luis Suárez, who had won the European Golden Shoe the year before at Liverpool.[119][120] Luis Enrique's system would feature quick transitions from defense to attack, led by the front three of Messi, Suárez and Neymar. The attacking trio, which colloquially became known as 'MSN', would break goalscoring records.[121] A hat-trick scored against Sevilla earlier in the season would also make him the all-time top scorer in La Liga, as he surpassed the 59-year record of 251 league goals held by Telmo Zarra.[122] After securing the La Liga title, the Copa del Rey, and the Champions League that year, Messi helped Barcelona become the first club to win the continental treble twice.[123][124] He would record 58 goals, but combined with Neymar and Suárez, the attacking trio scored a total of 122 goals in all competitions that season, a record in Spanish football.[125]

Messi opened the 2015–16 season by helping Barcelona's win over Sevilla in the UEFA Super Cup.[126] Messi capped off the year by winning the 2015 FIFA Club World Cup final over River Plate in Yokohama, collecting his fifth club trophy of the calendar year.[127] On 11 January 2016, Messi won the FIFA Ballon d'Or for a record fifth time in his career.[128] He would end the season by winning La Liga as well as the Copa del Rey again.[129] In total, Messi scored 41 goals, and Barcelona's attacking trio of him, Neymar and Suárez managed a Spanish record of 131 combined goals throughout the season, breaking the record they had set the previous season.[130]

The 2016–17 season would end with Messi winning the Supercopa de España and the Copa del Rey.[131][132] He would finish the season with 54 goals, while his 37 goals in La Liga saw him claim both the Pichichi and European Golden Boot Awards for the fourth time in his career.[133] Messi, Neymar and Suárez would combine for 110 goals by season's end. Neymar would depart for Paris Saint Germain the next year, leaving the attacking trio with a combined total of 363 goals over the course of three seasons.[134] Luis Enrique would also leave Barcelona at the end of the season after managing the club to a total of nine trophies during his three-year tenure.[135]

2017–2021: Final years at Barcelona

Messi, wearing the captain's armband, against Real Valladolid in 2018.
Messi would sign a new deal with Barcelona on 25 November 2017, his ninth contract with the club, keeping him with the club through 2021.[136] The 2017–18 season saw Messi achieving the domestic double, winning La Liga and the Copa del Rey once again.[137] He once again finished the season as the top scorer in La Liga, with 34 goals, which also saw him win his fifth European Golden Shoe award.[138] With the departure of former captain Andrés Iniesta in May 2018, Messi was named the team's new captain for the 2018–19 season.[139] He lifted his first trophy as Barcelona's captain, the Supercopa de España, following a 2–1 victory over Sevilla. He helped Barcelona clinch the La Liga title, his tenth but first as captain.[140] With 36 goals in 34 appearances that season, he won his sixth league Golden Boot trophy, equalling Zarra as the player with the most top-scorer awards in La Liga.[141][142] He also captured his sixth Golden Shoe award, and a record third consecutive award since the 2016–17 season.[143]

Messi would win his sixth Ballon d'Or, but the subsequent 2019–20 season saw Barcelona go trophyless for the first time since 2007–08.[144] Following a disappointing season, Barcelona announced that Messi sent the club "a document expressing his desire to leave", but Messi ultimately decided to fulfill the final year of his contract.[145][146] The 2020–21 season saw Messi surpass Xavi's record to reach a club record of 768 appearances.[147] He would lead the club to victory in the 2021 Copa del Rey final.[148][149] His last two seasons with Barcelona saw him lead La Liga in goal scoring, giving him a record-breaking total of eight Pichichi trophies.[150][151]

Messi became a free agent after his contract expired, with negotiations on a new deal complicated due to Barcelona's financial issues.[152][153] Barcelona would eventually announce that Messi would not be staying at the club, citing financial and structural obstacles posed by La Liga regulations as a reason for Messi's departure.[154][155] In a tearful press conference held at the Camp Nou, Messi confirmed that he would be leaving Barcelona.[156]

Paris Saint-Germain

Messi (middle) with PSG team-mates Kylian Mbappé (left) and Neymar.
On 10 August 2021, Messi joined Ligue 1 club Paris Saint-Germain (PSG), reuniting him with Neymar, for the 2021–22 season on a two-year deal until June 2023 with an option for an extra year.[157][158] Messi chose 30 as his squad number, the same he wore as a teenager when he made his senior debut for Barcelona.[159] He would make his debut with the club against Reims, made his first start and Champions League debut for the club against Club Brugge, and made his home debut in a match against Lyon[160][161][162] He scored his first goal for the club in a Champions League group stage win over former manager Pep Guardiola's Manchester City.[163] Having scored 40 goals at club and international level for the calendar year in addition to captaining Argentina to the 2021 Copa América, Messi received a record seventh Ballon d'Or.[164] He finished his debut season with PSG with 11 goals and 14 assists across all competitions, helping the club win their 10th Ligue 1 title.[165]

Beginning the 2022–23 season, Messi would win his second trophy with PSG in the Trophée des Champions.[166] A goal against Nice resulted in him surpassing Cristiano Ronaldo as the all-time highest goalscorer in European club football with 702 goals; during the match, he also achieved 1,000 career direct goal contributions at club level.[167][168] By the end of the season, he had 21 goals across all competitors and the highest number of assists in the league with 16, which helped PSG clinch their 11th Ligue 1 title and his second in a row.[169][170][171] Following the last game of the season, manager Christophe Galtier confirmed that it would be Messi's last for PSG, with the club confirming his departure two days later.[172]

Inter Miami

Messi with Inter Miami in the 2023 U.S. Open Cup.
Major League Soccer (MLS) club Inter Miami CF announced the signing of Messi on a two-and-a-half-year contract on 15 July 2023.[173][174] Messi made his 2023 debut for the club in a Leagues Cup match against Cruz Azul, scoring with a free-kick in stoppage time for a victory.[175] DeAndre Yedlin, the previous captain of Inter Miami, gave his armband to Messi, who took over as team captain.[176] Messi's arrival in the US was praised as a revelation, on and off the pitch, and his presence was credited for helping to raise the profile of MLS within the US and abroad. According to Goal, "Every game that he graces sparks a scramble for tickets, with plenty of A-list guests eager to watch him in action".[177] The frenzy over his arrival was dubbed "Messimania", and Inter Miami's No. 10 Messi jersey became the best-selling jersey in the league, and nearly the world.[178]

After scoring nine goals in his first six games for Miami, Messi led the team to the club's first-ever trophy, as it won the Leagues Cup against Nashville SC.[179] Messi made his MLS debut against the New York Red Bulls.[180] Miami would miss the playoffs, finishing 14th in the Eastern Conference, having gone winless in their last seven games.[181] On 30 October 2023, following his World Cup win with Argentina and Ligue 1 trophy with PSG, Messi was awarded a record-extending eighth Ballon d'Or.[182] He was also named Time Athlete of the Year, the first footballer ever to win the award.[183]

During the 2024 season, Messi broke the record for the most assists in a single MLS game with five assists, and broke the record for the most goal contributions in an MLS game with six, in a 6–2 win over the New York Red Bulls.[184] On 2 October, Messi scored a brace in a 3–2 win over Columbus Crew, clinching the Supporters' Shield, his 46th trophy.[185] In the final game of the regular season on 19 October against the New England Revolution, Messi scored his first hat-trick for the club in a 6–2 victory. Inter Miami's victory over the Revolution also allowed the club to finish with 74 points throughout the regular season, a league record for MLS. He would finish the regular season with 20 goals and 16 assists in 19 matches.[186] In doing so, he became Inter Miami's all-time leading goalscorer.[187]

Miami made its first postseason appearance in the 2024 MLS Cup playoffs but were eliminated in the first round after losing two games against Atlanta United FC. Messi would have his first postseason goal in the third game, a 3–2 loss.[188] He would be named the MLS Most Valuable Player following the conclusion of the regular season.[189]

During the 2025 season, Messi became the fastest person to reach 40 goals in league history.[190] He was featured in a Superbowl ad by Apple TV for their exclusive MLS coverage. In April he was reported to be negotiating a one-year contract extension to the end of the 2026 season, after the opening of the new Miami stadium.[190]

International career
Main article: Career of Lionel Messi § International career
As a dual Argentine-Spanish national, Messi was eligible to play for the national team of both countries.[191] He debuted for Argentina in 2004 for Argentina's U20 team against Paraguay, and was subsequently included in the squad for the 2005 South American U-20 Championship, where they would finish third.[192] Messi would then lead the team to victory in the 2005 FIFA World Youth Championship, his first success with Argentina. Finishing the tournament with six goals and two assists, he would also win the Golden Ball.[193][194][195]


Messi evades Brazil's Marcelo in the semi-final of the 2008 Summer Olympics.
Messi would make his debut with the senior national team in 2005, at age 18, coming off the bench in a friendly against Hungary.[196] Messi would have his first start in 2006 against Peru, and would score his first international goal in a friendly against Croatia.[197][198] His World Cup debut came in the 2006 FIFA World Cup as a substitute in the 74th minute against Serbia and Montenegro, assisting one goal and scoring the final one in their victory. This made him the youngest player to represent and score for Argentina in the World Cup.[199] He would represent Argentina again for the 2007 Copa América, where they would ultimately lose in the final. Messi was named the best young player of the tournament, having scored two goals and provided one assist.[200] The 2008 Summer Olympics would mark another major achievement with his country, as he led Argentina's U23 team to claim the Olympic gold medal over Nigeria. Messi registered two goals and three assists throughout, and was singled out by FIFA as the stand-out player from the tournament's best team.[201]


Messi in his number 10 shirt captaining Argentina in 2012.
With the international retirement of Juan Román Riquelme, Messi was given Argentina's number 10 shirt.[202] During a 2010 FIFA World Cup group stage match against Greece, where a majority of the starters rested due to a secured place in the knockout rounds, Messi would wear the captain's armband for the first time.[203] Argentina were ultimately eliminated in the quarterfinals against Germany during that tournament, but Messi was identified as one of the tournament's 10 best players due to his pace and creativity, despite failing to register a single goal and only having one assist.[204] Ahead of the 2011 Copa América, Argentina began building their team around Messi.[205] However, Messi would again be goalless during the tournament but had three assists. The team would ultimately lose to Uruguay in penalties during the quarter-finals.[206]


Messi against Germany in the 2014 FIFA World Cup final.
Following their unsuccessful performance, a 24-year-old Messi would be awarded the captaincy of the squad.[207] The next several years saw many frustrations for Messi due to his inability to lead Argentina to win an international trophy. During the 2014 FIFA World Cup, Messi and Argentina lost to Germany in the final, though Messi was awarded the Golden Ball as the best player of the tournament regardless due to his overall performance with four goals and an assist.[208][209] Argentina would lose to Chile on penalties in the 2015 Copa América final the next year. At the close of the tournament, Messi was reportedly selected to receive the Golden Ball award, having scored one goal and provided three assists, but he rejected the honour.[210] In the 2016 Copa América Centenario semi-final against the United States, a goal from Messi would put him ahead of Gabriel Batistuta as Argentina's all-time leading goalscorer in international matches.[211] However, Argentina would again fall to Chile on penalties in the final.[212] Messi would have five goals and four assists throughout the tournament.[213]

Losing three consecutive finals in three consecutive years caused Messi to retire from international football, but a nationwide campaign in Argentina helped convince him to reverse his decision.[212][214] He would return to the national team to lead them to the 2018 FIFA World Cup. Argentina were in jeopardy of missing the tournament on the last game of the qualifiers against Ecuador, but a hat-trick from Messi dramatically secured their entry.[215] They would go on to lose to France in the Round of 16 during the World Cup, with Messi having one goal and two assists in the tournament.[216] The next year, Messi would again represent Argentina in the 2019 Copa América, where he registered only a single goal and assist. They would lose to hosts Brazil in the semi-final but ended with a third-place finish after defeating Chile.[217] Despite not winning the tournament, this victory would mark the beginning of a 36-game unbeaten streak for Argentina that would last for over three years.[218]


Messi facing off against Érick Gutiérrez of Mexico in the 2022 FIFA World Cup group stage.
Messi would finally end Argentina's 28-year trophy drought in the 2021 Copa América, as they had not won an international tournament since 1993.[219] During a group stage match against Bolivia, he surpassed Javier Mascherano to become Argentina's most-capped player.[220] Argentina defeated Brazil in the final, and Messi was named the player of the tournament having been directly involved in nine out of the 12 goals scored by Argentina, scoring four of them and assisting five.[219] He captained Argentina to win another international trophy in the 2022 Finalissima against UEFA Euro 2020 winners Italy, where he was named player of the match after providing two assists.[221] At the 2022 FIFA World Cup, Messi led Argentina to its first World Cup victory in 36 years, scoring twice in the final to defeat France.[222] Having scored seven goals and assisting three during the tournament, Messi would again win the Golden Ball, becoming the first player to win it twice.[223] His appearance in the final also set new records for the most appearances (26) and direct goal contributions (21 – 13 goals and 8 assists) at the World Cup.[224]

A hat-trick in a 2023 friendly against Curaçao saw Messi reach 100 international goals, the third player and the first South American in history to achieve this milestone.[225] Later that year, a goal against Peru resulted in Messi becoming the all-time top goalscorer in CONMEBOL World Cup qualifiers.[226] During the 2024 Copa América semi-final against Canada, Messi scored his first and only goal of the tournament which also made him the second-highest international goalscorer of all time.[227] Argentina eventually won the final against Colombia for their second consecutive Copa América title, with Messi contributing one goal and assist overall while also setting a new record for most appearances (39) at Copa América.[228]

Player profile
Style of play

Messi prepares to shoot with his dominant left foot in the 2014 FIFA World Cup final.
Due to his short stature, Messi has a lower centre of gravity than taller players, which gives him greater agility, allowing him to change direction more quickly and evade opposing tackles;[229][230] this has led the Spanish media to dub him La Pulga Atómica ("The Atomic Flea").[231][232][233] Despite being physically unimposing, he possesses significant upper-body strength, which, combined with his low centre of gravity and resulting balance, aids him in withstanding physical challenges from opponents; he has consequently been noted for his lack of diving in a sport rife with playacting.[28][230][234] His short, strong legs allow him to excel in short bursts of acceleration while his quick feet enable him to retain control of the ball when dribbling at speed.[235] His former Barcelona manager Pep Guardiola once stated, "Messi is the only player that runs faster with the ball than he does without it."[236] Although he has improved his ability with his weaker foot since his mid-20s, Messi is predominantly a left-footed player; with the outside of his left foot, he usually begins dribbling runs, while he uses the inside of his foot to finish and provide passes and assists.[237][238]

A prolific goalscorer, Messi is known for his finishing, positioning, quick reactions, and ability to make attacking runs to beat the defensive line. He also functions in a playmaking role, courtesy of his vision and range of passing.[239] He has often been described as a magician; a conjurer, creating goals and opportunities where seemingly none exist.[240][241][242] Moreover, he is an accurate free kick and penalty kick taker.[230][243] As of May 2025, Messi ranks third all time in goals scored from direct free kicks with 67,[244] the most among active players.[245] He also has a penchant for scoring from chips.[246]


Messi's dribbling abilities allow him to weave past several defenders and orchestrate attacking plays.
Messi's pace and technical ability enable him to undertake individual dribbling runs towards goal, in particular during counterattacks, usually starting from the halfway line or the right side of the pitch.[234][243][247] He is widely considered to be one of the greatest dribblers of all time.[248][249] With regard to this ability, his former Argentina manager Diego Maradona has said of him, "The ball stays glued to his foot; I've seen great players in my career, but I've never seen anyone with Messi's ball control."[238] Beyond his individual qualities, he is also a well-rounded, hard-working team player, known for his creative combinations, in particular with former Barcelona midfielders Xavi and Andrés Iniesta.[229][230]

As his career advanced, and his athleticism and tendency to dribble diminished slightly with age, Messi began to dictate play in deeper areas of the pitch and developed into one of the best passers and playmakers in football history.[250][251][252] His work-rate off the ball and defensive responsibilities also decreased as his career progressed; by covering less ground on the pitch, and instead conserving his energy for short bursts of speed, he was able to improve his efficiency, movement, and positional play, and was also able to avoid muscular injuries, despite often playing a large number of matches throughout a particular season on a consistent basis. Indeed, while he was injury-prone in his early career, he was later able to improve his injury record by running less off the ball, and by adopting a stricter diet, training regime, and sleep schedule.[253]

Tactical positioning

A versatile forward, Messi often plays as a classic number 10.
Tactically, Messi plays in a free attacking role; a versatile player, he is capable of attacking on either wing or through the centre of the pitch. His favoured position in childhood was the playmaker behind two strikers, known as the enganche in Argentine football, but he began his career in Spain as a left-winger or left-sided forward.[254] Upon his first-team debut, he was moved onto the right wing by manager Frank Rijkaard; from this position, he could more easily cut through the defence into the middle of the pitch and curl shots on goal with his left foot, rather than predominantly cross balls for teammates.[236] Under Guardiola and subsequent managers, he most often played in a false nine role; positioned as a centre-forward or lone striker, he would roam the centre, often moving deep into midfield and drawing defenders with him, in order to create and exploit spaces for passes, other teammates' attacking runs off the ball, Messi's own dribbling runs, or combinations with Xavi and Iniesta.[38]

Under the stewardship of Luis Enrique, Messi initially returned to playing in the right-sided position that characterised much of his early career in the manager's 4–3–3 formation,[255][256] while he was increasingly deployed in a deeper, free playmaking role in later seasons.[257][258] Under manager Ernesto Valverde, Messi played in a variety of roles. While he occasionally continued to be deployed in a deeper role, from which he could make runs from behind into the box,[259] or even on the right wing[260] or as a false nine,[261][262] he was also used in a more offensive, central role in a 4–2–3–1,[258] or as a second striker in a 4–4–2 formation, where he was once again given the licence to drop deep, link-up with midfielders, orchestrate his team's attacking plays, and create chances for his attacking partner Luis Suárez.[263][264] With the Argentina national team, Messi has similarly played anywhere along the frontline. Under various managers, he has been employed on the right wing, as a false nine, as an out-and-out striker, in a supporting role alongside another forward, or in a deeper, free creative role as a classic number 10 playmaker or attacking midfielder behind the strikers.[265][266]

Reception
Messi is widely regarded as one of the two best players of his generation, alongside Portuguese forward Cristiano Ronaldo.[267] He is also considered one of the greatest footballers in the history of the sport.[268]

A prodigious talent as a teenager, Messi established himself among the world's best players before age 20.[269] Shortly after teammate Ronaldinho won the 2005 Ballon d'Or, he commented, "I'm not even the best at Barça" in reference to his 18-year-old protégé.[270] Four years later, after Messi won his first Ballon d'Or by a record margin,[81] the public debate regarding his qualities as a player moved beyond his status in contemporary football to the possibility that he was one of the greatest players in history.[24][234][271] An early proponent was his then-Barcelona manager Pep Guardiola, who, as early as August 2009, declared Messi to be the best player he had ever seen.[272] In the following years, this opinion gained greater acceptance among pundits, managers, former and current players.[92][273] By the end of Barça's second treble-winning season, the view of Messi as one of the greatest footballers of all time had become the apparent view among many fans and pundits in continental Europe.[274][275]

Messi would receive dismissals by critics throughout his career based on the fact that he had not won an international tournament at senior level with Argentina.[276][277][278] However, his subsequent victories in the 2021 Copa América and the 2022 FIFA World Cup resulted in him finally winning every top tier trophy at both the club and country levels, an achievement that many pundits felt cemented Messi's legacy.[268]

Comparisons with Cristiano Ronaldo
Main article: Messi–Ronaldo rivalry

Messi has been compared with Cristiano Ronaldo (left) throughout much of their careers.
Among his contemporary peers, Messi is most often compared and contrasted with Cristiano Ronaldo, who many consider his career rival.[267] Both achieved numerous individual accolades, won dozens of trophies for both club and country, and are the two leading goal scorers in history. Although Messi has at times denied any rivalry,[279][280] they are widely believed to push one another in their aim to be the best player in the world.[281] Pundits have compared the ongoing rivalry to past sports rivalries like the Muhammad Ali–Joe Frazier rivalry in boxing, the Prost–Senna rivalry in motorsport, and the tennis rivalries between Federer–Nadal and Borg–McEnroe.[282]

Fans and pundits alike regularly argue the individual merits of both players.[281][283] Messi is lauded for his combination of dribbling, playmaking, passing and goalscoring, while Ronaldo has received praise for his exceptional speed and athleticism, goalscoring skills, and performance under pressure.[284][285] Beyond their playing styles, the debate also revolves around their differing physiques – Ronaldo is 1.87 m (6 ft 1+1⁄2 in) with a muscular build, compared to Messi's smaller size – and contrasting public personalities with Ronaldo's self-confidence and theatrics a foil to Messi's humility.[286] Regarding individual achievements, Messi has won eight Ballons d'Or to Ronaldo's five,[287] eight FIFA World's Best Player awards to Ronaldo's five, and six European Golden Shoes to Ronaldo's four.[288] Off the pitch, Ronaldo is his direct competitor in terms of salary, sponsorships, and social media fanbase.[289]

Messi's head-to-head record against teams that feature Ronaldo consists of 15 wins, 9 draws, and 10 losses in competitive club matches, one win and loss each in international friendlies, and one win in a club friendly. The first competitive matchup between the two occurred in 2008, when Ronaldo's Manchester United were drawn to play Messi's Barcelona in the 2007–08 UEFA Champions League semi-finals, where Ronaldo and Manchester United would eventually advance 1–0 on aggregate, and go on to win the final.[290] The two players and their teams would meet again in the next year's Champions League, this time in the final, with Messi and Barcelona emerging as the victors after a 2–0 result.[291] After this, Ronaldo would transfer to Real Madrid, the main rivals of Barcelona, and from 2009–10 to 2017–18, Messi faced Ronaldo at least twice every season in El Clásico, which ranks among the world's most viewed annual sports events.[292][289] Ronaldo's would then transfer to Juventus in the summer of 2018; their final matchup in a competitive match would occur during a 2020–21 UEFA Champions League group stage match, where Ronaldo's two goals from the penalty spot helped Juventus to a 3–0 victory against Messi's Barcelona.[293] After Ronaldo left Real Madrid for Juventus, Messi stated: "I miss Cristiano. Although it was a bit difficult to see him win trophies, he gave La Liga prestige."[294]

Following Messi leading Argentina to victory in the 2022 World Cup, a number of football critics, commentators, and players have opined that Messi settled the debate between the two players.[295][296] Ronaldo himself declared a year later that his rivalry with Messi was over and "gone", after 36 official fixtures and 15 years of "sharing the stage".[297]

Comparisons with Diego Maradona
Main article: New Maradona
"I have seen the player who will inherit my place in Argentinian football and his name is Messi."

– Diego Maradona hailing the 18-year-old Messi as his successor in February 2006.[298]
Throughout his career, Messi has been compared with his compatriot Diego Maradona, who was also considered the best player of his generation and one of greatest in the history of the sport.[299][300] This was due to their short statures, their similar playing styles as diminutive, left-footed playmakers, and the fact that they both came from Argentina.[301] Initially, Messi was merely one of many young Argentine players to receive the "New Maradona" moniker, but as his career progressed, Messi proved his similarity beyond all previous contenders, establishing himself as the best player Argentina had produced since Maradona.[35][302] Even when Messi was 18 years old, Maradona called him the best player in the world and hailed him as his successor.[298] Messi and Maradona would work together as player and manager for Argentina's national side from 2008 through the 2010 FIFA World Cup, the latter thoroughly impressed with the former's skills.[303] It was during this period that Messi was given Argentina's number 10 shirt that Maradona famously wore. Maradona gave Messi his blessing, telling him: "the No 10 is yours. There's nobody better than you to wear it."[202]


Due to their similar size and style of play, Messi was constantly compared with his compatriot Diego Maradona by pundits and his countrymen.
During the early and middle parts of his career, Messi was generally held in lesser esteem than Maradona in Argentine society. Part of this had to do with Messi's lack of tournament success and perceived uneven output with the national team during this period – Maradona had famously led Argentina to victory in the 1986 FIFA World Cup with a dominant overall performance, which set expectations for Messi to do the same.[276][299][304] Also unlike Maradona, Messi never played in the Argentine Primera División, therefore depriving his countrymen a chance to watch him develop and prove himself, and through no fault of his own would do this overseas in La Liga instead.[28][304] Argentines also identified more with the fiery, extroverted and controversial Maradona who came from the slums, character traits that they felt aligned with their national values, as opposed to the reserved, introverted and unassuming Messi who had a comparably unremarkable upbringing in Rosario.[278][304][305] Several pundits, footballing figures, and Maradona himself would point to this temperament to question Messi's leadership capabilities for the national team.[276][306][307] Furthermore, Messi's lack of outward passion for the Albiceleste shirt, early tendency not to sing the national anthem, and disinclination to emotional displays have in the past led to the false perception that he felt more Catalan rather than truly Argentine.[206][308] However, despite having lived in Barcelona since age 13, Messi rejected the option of representing Spain internationally, saying: "Argentina is my country, my family, my way of expressing myself. I would change all my records to make the people in my country happy."[309]


A mural featuring both Maradona and Messi following Argentina's World Cup win in 2022.
Football journalist Tim Vickery stated the perception of Messi among Argentines changed in 2019, with Messi making a conscious effort to become "more one of the group, more Argentine".[308] Other pundits noted that Messi had grown more assertive as a leader during the 2019 Copa América by becoming more vocal with his teammates both on and off the pitch, finally singing the national anthem with the team before matches, and speaking with journalists at length after matches, the latter of which he rarely did for Barcelona.[310] Following the 2022 World Cup win for Messi and Argentina, Vickery felt that Messi would now be held in the same esteem by his compatriots as Maradona.[308] Former footballer turned journalist Jorge Valdano said he saw a "Maradonian" edge to Messi's performances during the tournament, while compatriot Osvaldo Ardiles mentioned that Messi's provoking actions against the Netherlands side during the quarter-final were "more of a Maradona reaction," further endearing Messi to his countrymen.[311][312] Messi himself later remarked that the World Cup victory "won over all the people of Argentina. Today 95% or 100% of Argentines love me and that's a beautiful feeling."[313]

In popular culture
Popularity

Messi's success on the pitch earned him several lucrative endorsement deals along with widespread recognition and popularity.
Messi was among the Time 100, an annual list of the world's most influential people, in 2011, 2012 and 2023.[314][315][316] According to a 2014 survey in 15 international markets, Messi was familiar to 87% of respondents around the world, of whom 78% perceived him favourably, making him the second-most recognised player globally, behind Cristiano Ronaldo, and the most likable of all contemporary players.[317][318] World Press Photo selected "The Final Game", a photo of Messi facing the World Cup trophy after Argentina's final defeat to Germany, as the best sports image of 2014.[319] On his economic impact on the city in which he plays, Terry Gibson called him a "tourist attraction".[320]

His fanbase on Facebook is among the largest of public figures: within seven hours of its launch in April 2011, Messi's Facebook page had nearly seven million followers, and by July 2023 he had over 114 million followers, the second highest for a sportsperson after Ronaldo.[321][322] He has over 500 million Instagram followers, the second highest for an individual and sportsperson after Ronaldo.[323] His World Cup celebration post from 18 December 2022 is the most liked post on Instagram with over 75 million likes.[324]

"""
docs = text_splitter.create_documents([text])
for doc in docs:
    print(doc.page_content + "\n---")